# Realistic dataset

In [1]:
data_path = '../data/baselines/PatchFinder'
top100_csv_filename = "top100_test.csv" # Name for the output CSV file
pred_top100_csv_filename = "predictions_top100_test.csv" # Name for the output CSV file

In [2]:
import os
import polars as pl


top100_df = pl.read_csv(os.path.join(data_path, top100_csv_filename))
pred_top100_df = pl.read_csv(os.path.join(data_path, pred_top100_csv_filename))


top100_df = (
    top100_df
    .join(
        pred_top100_df,
        on=set(top100_df.columns).intersection(set(pred_top100_df.columns)),
        how="left"
    )
)
top100_df

shape: (179_696, 13)
┌────────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬──────────┬───────────┐
│ cve        ┆ repo      ┆ commit_id ┆ similarit ┆ … ┆ precision ┆ f1       ┆ fused_f1 ┆ predictio │
│ ---        ┆ ---       ┆ ---       ┆ y         ┆   ┆ ---       ┆ ---      ┆ ---      ┆ n         │
│ str        ┆ str       ┆ str       ┆ ---       ┆   ┆ f64       ┆ f64      ┆ f64      ┆ ---       │
│            ┆           ┆           ┆ f64       ┆   ┆           ┆          ┆          ┆ f64       │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪══════════╪═══════════╡
│ CVE-2005-2 ┆ muttmua/m ┆ 4927240d1 ┆ 0.047721  ┆ … ┆ 0.50792   ┆ 0.378256 ┆ 0.425977 ┆ 0.000445  │
│ 351        ┆ utt       ┆ f8fca0806 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ df1e48e5b ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 09e…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2005-2 ┆ muttmua/m ┆ a327386c5 ┆ 0.053276  ┆ … ┆ 0.463529  ┆ 0.372788 ┆ 0.426064 ┆ 0.000006  │
│ 351        ┆ utt       ┆ bf676a832 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 1335fca84 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 915…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2005-2 ┆ muttmua/m ┆ f30dd8049 ┆ 0.055703  ┆ … ┆ 0.52324   ┆ 0.370582 ┆ 0.426285 ┆ 0.000005  │
│ 351        ┆ utt       ┆ 42eee1339 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ d59785cde ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 4d0…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2005-2 ┆ muttmua/m ┆ e31324465 ┆ 0.042647  ┆ … ┆ 0.464208  ┆ 0.383766 ┆ 0.426413 ┆ 0.000004  │
│ 351        ┆ utt       ┆ 7623f23e5 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ d9a8da698 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ a98…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2005-2 ┆ muttmua/m ┆ 848834424 ┆ 0.065582  ┆ … ┆ 0.485146  ┆ 0.360842 ┆ 0.426424 ┆ 0.00068   │
│ 351        ┆ utt       ┆ 235c85094 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 7c164ff78 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 2d4…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ …          ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …        ┆ …         │
│ CVE-2022-3 ┆ abersheer ┆ 24a2781b7 ┆ 0.175148  ┆ … ┆ 0.5624    ┆ 0.485179 ┆ 0.660327 ┆ 0.00001   │
│ 5411       ┆ an/rpc.py ┆ 3f8d500d8 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 405682e45 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 810…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2022-3 ┆ abersheer ┆ a04fa00d8 ┆ 0.222159  ┆ … ┆ 0.508194  ┆ 0.449864 ┆ 0.672023 ┆ 0.000016  │
│ 5411       ┆ an/rpc.py ┆ bcee13ec5 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 40b3e4275 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 8a6…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2022-3 ┆ abersheer ┆ 385950473 ┆ 0.217127  ┆ … ┆ 0.548692  ┆ 0.48857  ┆ 0.705697 ┆ 0.000009  │
│ 5411       ┆ an/rpc.py ┆ 8df9c9088 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ ad4ba81fc ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 542…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2022-3 ┆ abersheer ┆ e60aba3d9 ┆ 0.23777   ┆ … ┆ 0.498091  ┆ 0.479313 ┆ 0.717083 ┆ 0.000011  │
│ 5411       ┆ an/rpc.py ┆ 9297003a2 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 8069ce796 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 50a…      ┆           ┆   ┆           ┆          ┆          ┆           │
│ CVE-2022-3 ┆ abersheer ┆ 491e7a841 ┆ 0.221352  ┆ … ┆ 0.540861  ┆ 0.50769  ┆ 0.729042 ┆ 0.000013  │
│ 5411       ┆ an/rpc.py ┆ ed9a75479 ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 6d6ab047a ┆           ┆   ┆           ┆          ┆          ┆           │
│            ┆           ┆ 9fb…      ┆           ┆   ┆           ┆          ┆          ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴──────────┴───────────┘

In [4]:
import re

def find_cve_ids(text):
    """
    Finds all CVE ID references in a given text.
    
    Args:
        text (str): The input string to search for CVE IDs.
    
    Returns:
        list: A list of found CVE IDs.
    """
    cve_pattern = r'CVE-\d{4}-\d{4,}'
    return re.findall(cve_pattern, text)

In [ ]:
from datasets import load_dataset

patches_ds = load_dataset("andstor/cvevc_commits", "patches", split="test")

#explicit_patches = ddict.filter(lambda x: find_cve_ids(x['commit_message']), num_proc=10)
#implicit_patches = patches_ds.filter(lambda x: not find_cve_ids(x['commit_message']), num_proc=10)

In [42]:
from datasets import get_dataset_infos

infos = get_dataset_infos("andstor/cvevc_commits")

top_100_commit_ids = top100_df['commit_id'].to_list()
top_100_commit_data = []

In [ ]:
from tqdm import tqdm

non_patches_ds = load_dataset("andstor/cvevc_commits", "non_patches", split="test", streaming=True)
num_examples = infos["non_patches"].splits["test"].num_examples

for row in tqdm(non_patches_ds, total=num_examples):
    # Check if the row is in the top 100 DataFrame
    if row['commit_id'] in top_100_commit_ids:
        # Append the row to the top_100_commit_data list
        top_100_commit_data.append(row)

100%|██████████| 2150904/2150904 [1:05:39<00:00, 545.96it/s]

In [43]:
from tqdm import tqdm
from datasets import get_dataset_infos

patches_ds = load_dataset("andstor/cvevc_commits", "patches", split="test")
num_examples = infos["patches"].splits["test"].num_examples

for row in tqdm(patches_ds, total=num_examples):
    # Check if the row is in the top 100 DataFrame
    if row['commit_id'] in top_100_commit_ids:
        # Append the row to the top_100_commit_data list
        top_100_commit_data.append(row)

100%|██████████| 1453/1453 [00:01<00:00, 842.68it/s]

In [8]:
import pickle
# Save the top_100_commit_data list to a pickle file
with open('top_100_commit_data.pkl', 'wb') as f:
    pickle.dump(top_100_commit_data, f)

In [15]:
import pickle
with open('top_100_commit_data.pkl', 'rb') as f:
    top_100_commit_data = pickle.load(f)

In [16]:
import polars as pl
top_100_commit_df = pl.DataFrame(top_100_commit_data)
top_100_commit_df

shape: (93_978, 5)
┌──────────────────────┬──────────────────────┬──────────────────────┬─────────────────────┬───────┐
│ commit_id            ┆ repo                 ┆ commit_message       ┆ diff                ┆ label │
│ ---                  ┆ ---                  ┆ ---                  ┆ ---                 ┆ ---   │
│ str                  ┆ str                  ┆ str                  ┆ str                 ┆ i64   │
╞══════════════════════╪══════════════════════╪══════════════════════╪═════════════════════╪═══════╡
│ 388d0e6d391482ea8e86 ┆ 02strich/pykerberos  ┆ Added missing error  ┆ commit 388d0e6d3914 ┆ 0     │
│ 91efef8ef8…          ┆                      ┆ messge               ┆ 82ea8e8691e…        ┆       │
│                      ┆                      ┆                      ┆                     ┆       │
│ 481fc62b286fc2f1a5e8 ┆ 02strich/pykerberos  ┆ Merge pull request   ┆ commit 481fc62b286f ┆ 0     │
│ 286e402713…          ┆                      ┆ #23 from di…         ┆ c2f1a5e8286…        ┆       │
│ 5867201f1b9c682402aa ┆ 02strich/pykerberos  ┆ Adding missing       ┆ commit 5867201f1b9c ┆ 0     │
│ 9b495a654b…          ┆                      ┆ optional marker…     ┆ 682402aa9b4…        ┆       │
│ 39ec626539c355940cb2 ┆ 02strich/pykerberos  ┆ add winrm-style IOV  ┆ commit 39ec626539c3 ┆ 0     │
│ 908d23e35a…          ┆                      ┆ encryption…          ┆ 55940cb2908…        ┆       │
│ 17aeaef915e197a371eb ┆ 02strich/pykerberos  ┆ v1.2.4 release       ┆ commit 17aeaef915e1 ┆ 0     │
│ 49a4f9b6b8…          ┆                      ┆                      ┆ 97a371eb49a…        ┆       │
│                      ┆                      ┆ Changelog and …      ┆                     ┆       │
│ …                    ┆ …                    ┆ …                    ┆ …                   ┆ …     │
│ 395830d43349ed5bc063 ┆ zeit/serve           ┆ Rewrite project      ┆ commit 395830d43349 ┆ 1     │
│ 3c3f44c6cd…          ┆                      ┆ entirely (#374…      ┆ ed5bc0633c3…        ┆       │
│ c273f40a413d7f65abb8 ┆ zopefoundation/Acces ┆ LP #1047318: Tighten ┆ commit c273f40a413d ┆ 1     │
│ bf0f30bf14…          ┆ sControl             ┆ import re…           ┆ 7f65abb8bf0…        ┆       │
│ b42dd4badf803bb9fb71 ┆ zopefoundation/Acces ┆ Merge pull request   ┆ commit b42dd4badf80 ┆ 1     │
│ ac34cd9cb0…          ┆ sControl             ┆ from GHSA-q…         ┆ 3bb9fb71ac3…        ┆       │
│ 2dad81128250cb2e5d95 ┆ zopefoundation/Produ ┆ - Fix missing access ┆ commit 2dad81128250 ┆ 1     │
│ 0cddc9d3c0…          ┆ cts.Plugga…          ┆ control o…           ┆ cb2e5d950cd…        ┆       │
│ 7eead067898852ebd3e0 ┆ zopefoundation/Produ ┆ - Fix open redirect  ┆ commit 7eead0678988 ┆ 1     │
│ f143bc5129…          ┆ cts.Plugga…          ┆ issue in  …          ┆ 52ebd3e0f14…        ┆       │
└──────────────────────┴──────────────────────┴──────────────────────┴─────────────────────┴───────┘

In [17]:

cands_df = (
    top100_df
    .join(
        top_100_commit_df,
        on=['repo', 'commit_id', 'label',],
        how="inner"
    )
    .with_columns([
        (-pl.col("prediction")).rank("ordinal").over("cve").alias("rank")  # rank 1 = best
    ])
    .select(['cve', 'repo', 'commit_id', 'commit_message', 'diff', 'label', 'rank'])

)

cands_df

shape: (179_473, 7)
┌────────────────┬────────────────┬────────────────┬────────────────┬───────────────┬───────┬──────┐
│ cve            ┆ repo           ┆ commit_id      ┆ commit_message ┆ diff          ┆ label ┆ rank │
│ ---            ┆ ---            ┆ ---            ┆ ---            ┆ ---           ┆ ---   ┆ ---  │
│ str            ┆ str            ┆ str            ┆ str            ┆ str           ┆ i64   ┆ u32  │
╞════════════════╪════════════════╪════════════════╪════════════════╪═══════════════╪═══════╪══════╡
│ CVE-2005-2351  ┆ muttmua/mutt   ┆ 4927240d1f8fca ┆ automatic      ┆ commit 492724 ┆ 0     ┆ 7    │
│                ┆                ┆ 0806df1e48e5b0 ┆ post-release   ┆ 0d1f8fca0806d ┆       ┆      │
│                ┆                ┆ 9e…            ┆ commit …       ┆ f1e4…         ┆       ┆      │
│ CVE-2005-2351  ┆ muttmua/mutt   ┆ a327386c5bf676 ┆ Stable branch  ┆ commit a32738 ┆ 0     ┆ 51   │
│                ┆                ┆ a8321335fca849 ┆ quick fix for  ┆ 6c5bf676a8321 ┆       ┆      │
│                ┆                ┆ 15…            ┆ pa…            ┆ 335f…         ┆       ┆      │
│ CVE-2005-2351  ┆ muttmua/mutt   ┆ f30dd804942eee ┆ This small     ┆ commit f30dd8 ┆ 0     ┆ 59   │
│                ┆                ┆ 1339d59785cde4 ┆ patch:         ┆ 04942eee1339d ┆       ┆      │
│                ┆                ┆ d0…            ┆                ┆ 5978…         ┆       ┆      │
│                ┆                ┆                ┆ * catches a…   ┆               ┆       ┆      │
│ CVE-2005-2351  ┆ muttmua/mutt   ┆ e313244657623f ┆ # changelog    ┆ commit e31324 ┆ 0     ┆ 92   │
│                ┆                ┆ 23e5d9a8da698a ┆ commit         ┆ 4657623f23e5d ┆       ┆      │
│                ┆                ┆ 98…            ┆                ┆ 9a8d…         ┆       ┆      │
│ CVE-2005-2351  ┆ muttmua/mutt   ┆ 848834424235c8 ┆ Fix            ┆ commit 848834 ┆ 0     ┆ 6    │
│                ┆                ┆ 50947c164ff782 ┆ next_token()   ┆ 424235c850947 ┆       ┆      │
│                ┆                ┆ d4…            ┆ oob read.  (c… ┆ c164…         ┆       ┆      │
│ …              ┆ …              ┆ …              ┆ …              ┆ …             ┆ …     ┆ …    │
│ CVE-2022-35411 ┆ abersheeran/rp ┆ 24a2781b73f8d5 ┆ Update         ┆ commit 24a278 ┆ 0     ┆ 91   │
│                ┆ c.py           ┆ 00d8405682e458 ┆ description    ┆ 1b73f8d500d84 ┆       ┆      │
│                ┆                ┆ 10…            ┆                ┆ 0568…         ┆       ┆      │
│ CVE-2022-35411 ┆ abersheeran/rp ┆ a04fa00d8bcee1 ┆ More tests     ┆ commit a04fa0 ┆ 0     ┆ 33   │
│                ┆ c.py           ┆ 3ec540b3e42758 ┆                ┆ 0d8bcee13ec54 ┆       ┆      │
│                ┆                ┆ a6…            ┆                ┆ 0b3e…         ┆       ┆      │
│ CVE-2022-35411 ┆ abersheeran/rp ┆ 3859504738df9c ┆ Update         ┆ commit 385950 ┆ 0     ┆ 94   │
│                ┆ c.py           ┆ 9088ad4ba81fc5 ┆ README.md      ┆ 4738df9c9088a ┆       ┆      │
│                ┆                ┆ 42…            ┆                ┆ d4ba…         ┆       ┆      │
│ CVE-2022-35411 ┆ abersheeran/rp ┆ e60aba3d992970 ┆ Add            ┆ commit e60aba ┆ 0     ┆ 73   │
│                ┆ c.py           ┆ 03a28069ce7965 ┆ CBORSerializer ┆ 3d99297003a28 ┆       ┆      │
│                ┆                ┆ 0a…            ┆ in README      ┆ 069c…         ┆       ┆      │
│                ┆                ┆                ┆                ┆               ┆       ┆      │
│ CVE-2022-35411 ┆ abersheeran/rp ┆ 491e7a841ed9a7 ┆ PickleSerializ ┆ commit 491e7a ┆ 1     ┆ 45   │
│                ┆ c.py           ┆ 54796d6ab047a9 ┆ er is turned   ┆ 841ed9a754796 ┆       ┆      │
│                ┆                ┆ fb…            ┆ off…           ┆ d6ab…         ┆       ┆      │
└────────────────┴────────────────┴────────────────┴────────────────┴───────────────┴───────┴──────┘

In [18]:
from datasets import load_dataset
cve_ds = load_dataset("andstor/cvevc_cve", split="test")
cve_df = cve_ds.to_polars()

/Users/andrestorhaug/Code/Projects/agentic-security-patch-classification-replication-package/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

<function random_array at 0x3d84127a0>
<function random at 0x3d8412ac0>
<function rand at 0x3d8412c00>

In [24]:
# Add cve data to the top 100 commit data"
cve_cands_df = (
    cands_df
    .join(
        cve_df,
        on=["cve"],
        how="inner"
    )
    .select(['cve', 'desc', 'repo', 'commit_id', 'commit_message', 'diff', 'label', 'rank'])
    .sort("cve")
)
cve_cands_df

shape: (179_473, 8)
┌─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬───────┬──────┐
│ cve         ┆ desc        ┆ repo        ┆ commit_id   ┆ commit_mess ┆ diff        ┆ label ┆ rank │
│ ---         ┆ ---         ┆ ---         ┆ ---         ┆ age         ┆ ---         ┆ ---   ┆ ---  │
│ str         ┆ str         ┆ str         ┆ str         ┆ ---         ┆ str         ┆ i64   ┆ u32  │
│             ┆             ┆             ┆             ┆ str         ┆             ┆       ┆      │
╞═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═══════╪══════╡
│ CVE-2005-23 ┆ Mutt before ┆ muttmua/mut ┆ 4927240d1f8 ┆ automatic   ┆ commit 4927 ┆ 0     ┆ 7    │
│ 51          ┆ 1.5.20      ┆ t           ┆ fca0806df1e ┆ post-releas ┆ 240d1f8fca0 ┆       ┆      │
│             ┆ patch 7     ┆             ┆ 48e5b09e…   ┆ e commit …  ┆ 806df1e4…   ┆       ┆      │
│             ┆ all…        ┆             ┆             ┆             ┆             ┆       ┆      │
│ CVE-2005-23 ┆ Mutt before ┆ muttmua/mut ┆ a327386c5bf ┆ Stable      ┆ commit a327 ┆ 0     ┆ 51   │
│ 51          ┆ 1.5.20      ┆ t           ┆ 676a8321335 ┆ branch      ┆ 386c5bf676a ┆       ┆      │
│             ┆ patch 7     ┆             ┆ fca84915…   ┆ quick fix   ┆ 8321335f…   ┆       ┆      │
│             ┆ all…        ┆             ┆             ┆ for pa…     ┆             ┆       ┆      │
│ CVE-2005-23 ┆ Mutt before ┆ muttmua/mut ┆ f30dd804942 ┆ This small  ┆ commit f30d ┆ 0     ┆ 59   │
│ 51          ┆ 1.5.20      ┆ t           ┆ eee1339d597 ┆ patch:      ┆ d804942eee1 ┆       ┆      │
│             ┆ patch 7     ┆             ┆ 85cde4d0…   ┆             ┆ 339d5978…   ┆       ┆      │
│             ┆ all…        ┆             ┆             ┆ * catches   ┆             ┆       ┆      │
│             ┆             ┆             ┆             ┆ a…          ┆             ┆       ┆      │
│ CVE-2005-23 ┆ Mutt before ┆ muttmua/mut ┆ e3132446576 ┆ # changelog ┆ commit e313 ┆ 0     ┆ 92   │
│ 51          ┆ 1.5.20      ┆ t           ┆ 23f23e5d9a8 ┆ commit      ┆ 244657623f2 ┆       ┆      │
│             ┆ patch 7     ┆             ┆ da698a98…   ┆             ┆ 3e5d9a8d…   ┆       ┆      │
│             ┆ all…        ┆             ┆             ┆             ┆             ┆       ┆      │
│ CVE-2005-23 ┆ Mutt before ┆ muttmua/mut ┆ 84883442423 ┆ Fix next_to ┆ commit 8488 ┆ 0     ┆ 6    │
│ 51          ┆ 1.5.20      ┆ t           ┆ 5c850947c16 ┆ ken() oob   ┆ 34424235c85 ┆       ┆      │
│             ┆ patch 7     ┆             ┆ 4ff782d4…   ┆ read.  (c…  ┆ 0947c164…   ┆       ┆      │
│             ┆ all…        ┆             ┆             ┆             ┆             ┆       ┆      │
│ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …     ┆ …    │
│ CVE-2022-35 ┆ rpc.py      ┆ abersheeran ┆ 24a2781b73f ┆ Update      ┆ commit 24a2 ┆ 0     ┆ 91   │
│ 411         ┆ through     ┆ /rpc.py     ┆ 8d500d84056 ┆ description ┆ 781b73f8d50 ┆       ┆      │
│             ┆ 0.6.0       ┆             ┆ 82e45810…   ┆             ┆ 0d840568…   ┆       ┆      │
│             ┆ allows Re…  ┆             ┆             ┆             ┆             ┆       ┆      │
│ CVE-2022-35 ┆ rpc.py      ┆ abersheeran ┆ a04fa00d8bc ┆ More tests  ┆ commit a04f ┆ 0     ┆ 33   │
│ 411         ┆ through     ┆ /rpc.py     ┆ ee13ec540b3 ┆             ┆ a00d8bcee13 ┆       ┆      │
│             ┆ 0.6.0       ┆             ┆ e42758a6…   ┆             ┆ ec540b3e…   ┆       ┆      │
│             ┆ allows Re…  ┆             ┆             ┆             ┆             ┆       ┆      │
│ CVE-2022-35 ┆ rpc.py      ┆ abersheeran ┆ 3859504738d ┆ Update      ┆ commit 3859 ┆ 0     ┆ 94   │
│ 411         ┆ through     ┆ /rpc.py     ┆ f9c9088ad4b ┆ README.md   ┆ 504738df9c9 ┆       ┆      │
│             ┆ 0.6.0       ┆             ┆ a81fc542…   ┆             ┆ 088ad4ba…   ┆       ┆      │
│             ┆ allows Re…  ┆             ┆             ┆             ┆             ┆       ┆      │
│ CVE-2022-35 ┆ rpc.py      ┆ abersheeran ┆ e60aba3d992 ┆ Add CBORSer ┆ commit e60a ┆ 0     ┆ 73   │
│ 411         ┆ through     ┆ /rpc.py     ┆ 97003a28069 ┆ ializer in  ┆ ba3d9929700 ┆       ┆      │
│             ┆ 0.6.0       ┆             ┆ ce79650a…   ┆ README      ┆ 3a28069c…   ┆       ┆      │
│             ┆ allows Re…  ┆             ┆             ┆             ┆             ┆       ┆      │
│ CVE-2022-35 ┆ rpc.py      ┆ abersheeran ┆ 491e7a841ed ┆ PickleSeria ┆ commit 491e ┆ 1     ┆ 45   │
│ 411         ┆ through     ┆ /rpc.py     ┆ 9a754796d6a ┆ lizer is    ┆ 7a841ed9a75 ┆       ┆      │
│             ┆ 0.6.0       ┆             ┆ b047a9fb…   ┆ turned off… ┆ 4796d6ab…   ┆       ┆      │
│             ┆ allows Re…  ┆             ┆             ┆             ┆             ┆       ┆      │
└─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴───────┴──────┘

In [27]:
cve_cands_df["diff"].is_null().sum()

0

In [26]:
from datasets import Dataset
cve_cands_ds = Dataset.from_polars(cve_cands_df, split="test")
cve_cands_ds

Dataset({
    features: ['cve', 'desc', 'repo', 'commit_id', 'commit_message', 'diff', 'label', 'rank'],
    num_rows: 179473
})

In [28]:
cve_cands_ds.push_to_hub("andstor/cvevc_candidates", config_name="PatchFinder_top100", private=False, max_shard_size="250MB")

Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 67.62ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :  30%|███       | 14.1MB / 46.8MB, 23.6MB/s

Processing Files (0 / 1)                :  31%|███▏      | 14.7MB / 46.8MB, 14.7MB/s
Processing Files (0 / 1)                :  33%|███▎      | 15.2MB / 46.8MB, 12.7MB/s
Processing Files (0 / 1)                :  42%|████▏     | 19.4MB / 46.8MB, 13.9MB/s
Processing Files (0 / 1)                :  47%|████▋     | 22.1MB / 46.8MB, 13.8MB/s
Processing Files (0 / 1)                :  53%|█████▎    | 24.7MB / 46.8MB, 13.7MB/s
Processing Files (0 / 1)                :  60%|█████▉    | 27.9MB / 46.8MB, 13.9MB/s
Processing Files (0 / 1)                :  66%|██████▋   | 31.1MB / 46.8MB, 14.1MB/s
Processing Files (0 / 1)                :  71%|███████   | 33.2MB / 46.8MB, 13.8MB/s
Processing Files (0 / 1)                :  80%|████████  | 37.4MB / 46.8MB, 14.4MB/s
Processing Files (0 / 1)                :  88%|████████▊ | 41.1MB / 46.8MB, 14.7MB/s
Processing Files (0 / 1)                :  95%|█████████▍| 44.3MB / 46.8MB, 14.8MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 46.4MB / 46.8MB, 14.5MB/s


Processing Files (1 / 1)                : 100%|██████████| 46.8MB / 46.8MB, 12.3MB/s


Processing Files (1 / 1)                : 100%|██████████| 46.8MB / 46.8MB, 11.1MB/s
New Data Upload                         : 100%|██████████| 33.1MB / 33.1MB, 7.89MB/s
                                        : 100%|██████████| 46.8MB / 46.8MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 103.02ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :  12%|█▏        | 3.75MB / 31.9MB, 18.8MB/s
Processing Files (0 / 1)                :  18%|█▊        | 5.90MB / 31.9MB, 14.7MB/s
Processing Files (0 / 1)                :  27%|██▋       | 8.58MB / 31.9MB, 14.3MB/s
Processing Files (0 / 1)                :  37%|███▋      | 11.8MB / 31.9MB, 14.8MB/s
Processing Files (0 / 1)                :  45%|████▌     | 14.5MB / 31.9MB, 14.5MB/s
Processing Files (0 / 1)                :  54%|█████▎    | 17.2MB / 31.9MB, 14.3MB/s
Processing Files (0 / 1)                :  62%|██████▏   | 19.8MB / 31.9MB, 14.2MB/s
Processing Files (0 / 1)                :  71%|███████   | 22.5MB / 31.9MB, 14.1MB/s
Processing Files (0 / 1)                :  81%|████████  | 25.7MB / 31.9MB, 14.3MB/s
Processing Files (0 / 1)                :  89%|████████▉ | 28.4MB / 31.9MB, 14.2MB/s
Processing Files (0 / 1)                :  97%|█████████▋| 31.1MB / 31.9MB, 14.1MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 31.6MB / 31.9MB, 13.2MB/s


Processing Files (1 / 1)                : 100%|██████████| 31.9MB / 31.9MB, 10.6MB/s

Processing Files (1 / 1)                : 100%|██████████| 31.9MB / 31.9MB, 9.98MB/s
New Data Upload                         : 100%|██████████| 31.9MB / 31.9MB, 9.98MB/s
                                        : 100%|██████████| 31.9MB / 31.9MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 78.75ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :   9%|▉         | 3.71MB / 40.7MB, 18.6MB/s
Processing Files (0 / 1)                :  16%|█▌        | 6.36MB / 40.7MB, 16.0MB/s
Processing Files (0 / 1)                :  23%|██▎       | 9.54MB / 40.7MB, 15.9MB/s
Processing Files (0 / 1)                :  31%|███▏      | 12.7MB / 40.7MB, 15.9MB/s
Processing Files (0 / 1)                :  39%|███▉      | 15.9MB / 40.7MB, 15.9MB/s
Processing Files (0 / 1)                :  47%|████▋     | 19.1MB / 40.7MB, 15.9MB/s
Processing Files (0 / 1)                :  53%|█████▎    | 21.7MB / 40.7MB, 15.5MB/s
Processing Files (0 / 1)                :  61%|██████▏   | 24.9MB / 40.7MB, 15.6MB/s
Processing Files (0 / 1)                :  69%|██████▉   | 28.1MB / 40.7MB, 15.6MB/s
Processing Files (0 / 1)                :  77%|███████▋  | 31.3MB / 40.7MB, 15.7MB/s
Processing Files (0 / 1)                :  85%|████████▍ | 34.5MB / 40.7MB, 15.7MB/s
Processing Files (0 / 1)                :  93%|█████████▎| 37.6MB / 40.7MB, 15.7MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 40.3MB / 40.7MB, 15.5MB/s




Processing Files (1 / 1)                : 100%|██████████| 40.7MB / 40.7MB, 11.3MB/s

Processing Files (1 / 1)                : 100%|██████████| 40.7MB / 40.7MB, 10.7MB/s
New Data Upload                         : 100%|██████████| 40.7MB / 40.7MB, 10.7MB/s
                                        : 100%|██████████| 40.7MB / 40.7MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 74.40ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :   8%|▊         | 3.71MB / 45.0MB,   ???B/s
Processing Files (0 / 1)                :  13%|█▎        | 5.83MB / 45.0MB, 10.6MB/s

Processing Files (0 / 1)                :  20%|██        | 9.01MB / 45.0MB, 8.85MB/s
Processing Files (0 / 1)                :  25%|██▍       | 11.1MB / 45.0MB, 9.28MB/s
Processing Files (0 / 1)                :  31%|███       | 13.8MB / 45.0MB, 10.1MB/s
Processing Files (0 / 1)                :  35%|███▌      | 15.9MB / 45.0MB, 10.2MB/s
Processing Files (0 / 1)                :  41%|████      | 18.5MB / 45.0MB, 10.6MB/s
Processing Files (0 / 1)                :  47%|████▋     | 21.2MB / 45.0MB, 10.9MB/s
Processing Files (0 / 1)                :  53%|█████▎    | 23.8MB / 45.0MB, 11.2MB/s
Processing Files (0 / 1)                :  58%|█████▊    | 26.0MB / 45.0MB, 11.1MB/s
Processing Files (0 / 1)                :  65%|██████▍   | 29.1MB / 45.0MB, 11.6MB/s
Processing Files (0 / 1)                :  71%|███████   | 31.8MB / 45.0MB, 11.7MB/s
Processing Files (0 / 1)                :  77%|███████▋  | 34.4MB / 45.0MB, 11.8MB/s
Processing Files (0 / 1)                :  82%|████████▏ | 37.1MB / 45.0MB, 11.9MB/s
Processing Files (0 / 1)                :  88%|████████▊ | 39.7MB / 45.0MB, 12.0MB/s
Processing Files (0 / 1)                :  95%|█████████▌| 42.9MB / 45.0MB, 12.3MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 44.5MB / 45.0MB, 12.0MB/s




Processing Files (1 / 1)                : 100%|██████████| 45.0MB / 45.0MB, 9.38MB/s

Processing Files (1 / 1)                : 100%|██████████| 45.0MB / 45.0MB, 8.97MB/s
New Data Upload                         : 100%|██████████| 45.0MB / 45.0MB, 8.97MB/s
                                        : 100%|██████████| 45.0MB / 45.0MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 88.76ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :  10%|▉         | 3.72MB / 37.6MB,   ???B/s
Processing Files (0 / 1)                :  14%|█▍        | 5.31MB / 37.6MB, 7.99MB/s
Processing Files (0 / 1)                :  23%|██▎       | 8.50MB / 37.6MB, 12.0MB/s
Processing Files (0 / 1)                :  31%|███       | 11.7MB / 37.6MB, 13.3MB/s
Processing Files (0 / 1)                :  38%|███▊      | 14.3MB / 37.6MB, 13.3MB/s
Processing Files (0 / 1)                :  47%|████▋     | 17.5MB / 37.6MB, 13.8MB/s
Processing Files (0 / 1)                :  55%|█████▌    | 20.7MB / 37.6MB, 14.2MB/s
Processing Files (0 / 1)                :  64%|██████▎   | 23.9MB / 37.6MB, 14.4MB/s
Processing Files (0 / 1)                :  72%|███████▏  | 27.1MB / 37.6MB, 14.6MB/s
Processing Files (0 / 1)                :  81%|████████  | 30.3MB / 37.6MB, 14.8MB/s
Processing Files (0 / 1)                :  89%|████████▉ | 33.5MB / 37.6MB, 14.9MB/s
Processing Files (0 / 1)                :  97%|█████████▋| 36.7MB / 37.6MB, 15.0MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 37.2MB / 37.6MB, 13.9MB/s



Processing Files (1 / 1)                : 100%|██████████| 37.6MB / 37.6MB, 10.6MB/s

Processing Files (1 / 1)                : 100%|██████████| 37.6MB / 37.6MB, 9.97MB/s
New Data Upload                         : 100%|██████████| 37.6MB / 37.6MB, 9.97MB/s
                                        : 100%|██████████| 37.6MB / 37.6MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 78.16ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :   9%|▉         | 3.77MB / 41.6MB,   ???B/s
Processing Files (0 / 1)                :  14%|█▍        | 5.90MB / 41.6MB, 10.7MB/s
Processing Files (0 / 1)                :  22%|██▏       | 9.10MB / 41.6MB, 13.4MB/s
Processing Files (0 / 1)                :  30%|██▉       | 12.3MB / 41.6MB, 14.2MB/s
Processing Files (0 / 1)                :  37%|███▋      | 15.5MB / 41.6MB, 14.7MB/s
Processing Files (0 / 1)                :  45%|████▍     | 18.7MB / 41.6MB, 14.9MB/s
Processing Files (0 / 1)                :  53%|█████▎    | 21.9MB / 41.6MB, 15.1MB/s
Processing Files (0 / 1)                :  60%|██████    | 25.1MB / 41.6MB, 15.2MB/s
Processing Files (0 / 1)                :  68%|██████▊   | 28.3MB / 41.6MB, 15.3MB/s
Processing Files (0 / 1)                :  76%|███████▌  | 31.5MB / 41.6MB, 15.4MB/s
Processing Files (0 / 1)                :  83%|████████▎ | 34.7MB / 41.6MB, 15.5MB/s
Processing Files (0 / 1)                :  91%|█████████ | 37.9MB / 41.6MB, 15.5MB/s
Processing Files (0 / 1)                :  99%|█████████▊| 41.1MB / 41.6MB, 15.6MB/s
Processing Files (0 / 1)                : 100%|█████████▉| 41.6MB / 41.6MB, 14.6MB/s



Processing Files (1 / 1)                : 100%|██████████| 41.6MB / 41.6MB, 11.1MB/s



Processing Files (1 / 1)                : 100%|██████████| 41.6MB / 41.6MB, 9.47MB/s
New Data Upload                         : 100%|██████████| 41.6MB / 41.6MB, 9.47MB/s
                                        : 100%|██████████| 41.6MB / 41.6MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 64.13ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :   7%|▋         | 3.71MB / 51.9MB, 18.5MB/s
Processing Files (0 / 1)                :  11%|█         | 5.83MB / 51.9MB, 14.5MB/s
Processing Files (0 / 1)                :  15%|█▌        | 7.95MB / 51.9MB, 13.3MB/s
Processing Files (0 / 1)                :  19%|█▉        | 10.1MB / 51.9MB, 12.6MB/s
Processing Files (0 / 1)                :  25%|██▍       | 12.7MB / 51.9MB, 12.7MB/s
Processing Files (0 / 1)                :  29%|██▊       | 14.8MB / 51.9MB, 12.4MB/s
Processing Files (0 / 1)                :  34%|███▎      | 17.5MB / 51.9MB, 12.5MB/s
Processing Files (0 / 1)                :  40%|███▉      | 20.7MB / 51.9MB, 12.9MB/s
Processing Files (0 / 1)                :  44%|████▍     | 22.8MB / 51.9MB, 12.7MB/s
Processing Files (0 / 1)                :  49%|████▉     | 25.4MB / 51.9MB, 12.7MB/s
Processing Files (0 / 1)                :  52%|█████▏    | 27.0MB / 51.9MB, 12.3MB/s
Processing Files (0 / 1)                :  55%|█████▌    | 28.6MB / 51.9MB, 11.9MB/s

Processing Files (0 / 1)                :  60%|██████    | 31.3MB / 51.9MB, 11.2MB/s

Processing Files (0 / 1)                :  62%|██████▏   | 32.3MB / 51.9MB, 10.1MB/s
Processing Files (0 / 1)                :  64%|██████▍   | 33.4MB / 51.9MB, 9.82MB/s
Processing Files (0 / 1)                :  66%|██████▋   | 34.5MB / 51.9MB, 9.57MB/s
Processing Files (0 / 1)                :  68%|██████▊   | 35.5MB / 51.9MB, 9.35MB/s
Processing Files (0 / 1)                :  71%|███████▏  | 37.1MB / 51.9MB, 9.28MB/s
Processing Files (0 / 1)                :  74%|███████▎  | 38.2MB / 51.9MB, 9.09MB/s
Processing Files (0 / 1)                :  76%|███████▌  | 39.2MB / 51.9MB, 8.92MB/s
Processing Files (0 / 1)                :  80%|███████▉  | 41.4MB / 51.9MB, 8.99MB/s
Processing Files (0 / 1)                :  82%|████████▏ | 42.4MB / 51.9MB, 8.84MB/s
Processing Files (0 / 1)                :  85%|████████▍ | 44.0MB / 51.9MB, 8.80MB/s
Processing Files (0 / 1)                :  88%|████████▊ | 45.6MB / 51.9MB, 8.77MB/s
Processing Files (0 / 1)                :  92%|█████████▏| 47.7MB / 51.9MB, 8.84MB/s
Processing Files (0 / 1)                :  95%|█████████▍| 49.3MB / 51.9MB, 8.81MB/s
Processing Files (0 / 1)                :  98%|█████████▊| 50.9MB / 51.9MB, 8.78MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 51.4MB / 51.9MB, 8.57MB/s




Processing Files (1 / 1)                : 100%|██████████| 51.9MB / 51.9MB, 7.42MB/s

Processing Files (1 / 1)                : 100%|██████████| 51.9MB / 51.9MB, 7.21MB/s
New Data Upload                         : 100%|██████████| 51.9MB / 51.9MB, 7.21MB/s
                                        : 100%|██████████| 51.9MB / 51.9MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 66.79ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :   0%|          | 16.3kB / 52.1MB,   ???B/s
Processing Files (0 / 1)                :   7%|▋         | 3.72MB / 52.1MB, 18.6MB/s
Processing Files (0 / 1)                :   9%|▉         | 4.78MB / 52.1MB, 11.9MB/s
Processing Files (0 / 1)                :  13%|█▎        | 6.90MB / 52.1MB, 11.5MB/s
Processing Files (0 / 1)                :  16%|█▋        | 8.49MB / 52.1MB, 10.6MB/s
Processing Files (0 / 1)                :  19%|█▉        | 10.1MB / 52.1MB, 10.1MB/s
Processing Files (0 / 1)                :  22%|██▏       | 11.7MB / 52.1MB, 9.71MB/s
Processing Files (0 / 1)                :  25%|██▌       | 13.2MB / 52.1MB, 9.46MB/s
Processing Files (0 / 1)                :  29%|██▉       | 15.4MB / 52.1MB, 9.60MB/s
Processing Files (0 / 1)                :  33%|███▎      | 17.0MB / 52.1MB, 9.41MB/s
Processing Files (0 / 1)                :  36%|███▌      | 18.5MB / 52.1MB, 9.27MB/s
Processing Files (0 / 1)                :  39%|███▊      | 20.1MB / 52.1MB, 9.15MB/s
Processing Files (0 / 1)                :  43%|████▎     | 22.2MB / 52.1MB, 9.27MB/s
Processing Files (0 / 1)                :  46%|████▌     | 23.8MB / 52.1MB, 9.16MB/s
Processing Files (0 / 1)                :  49%|████▉     | 25.4MB / 52.1MB, 9.08MB/s
Processing Files (0 / 1)                :  53%|█████▎    | 27.5MB / 52.1MB, 9.18MB/s
Processing Files (0 / 1)                :  56%|█████▌    | 29.1MB / 52.1MB, 9.10MB/s
Processing Files (0 / 1)                :  59%|█████▉    | 30.7MB / 52.1MB, 9.03MB/s
Processing Files (0 / 1)                :  62%|██████▏   | 32.3MB / 52.1MB, 8.97MB/s
Processing Files (0 / 1)                :  66%|██████▌   | 34.4MB / 52.1MB, 9.06MB/s
Processing Files (0 / 1)                :  69%|██████▉   | 36.0MB / 52.1MB, 9.00MB/s
Processing Files (0 / 1)                :  73%|███████▎  | 38.1MB / 52.1MB, 9.08MB/s
Processing Files (0 / 1)                :  76%|███████▌  | 39.7MB / 52.1MB, 9.02MB/s
Processing Files (0 / 1)                :  79%|███████▉  | 41.3MB / 52.1MB, 8.98MB/s
Processing Files (0 / 1)                :  83%|████████▎ | 43.4MB / 52.1MB, 9.04MB/s
Processing Files (0 / 1)                :  86%|████████▋ | 45.0MB / 52.1MB, 9.00MB/s
Processing Files (0 / 1)                :  90%|█████████ | 47.1MB / 52.1MB, 9.06MB/s
Processing Files (0 / 1)                :  93%|█████████▎| 48.7MB / 52.1MB, 9.02MB/s
Processing Files (0 / 1)                :  98%|█████████▊| 50.8MB / 52.1MB, 9.08MB/s
Processing Files (0 / 1)                : 100%|█████████▉| 51.9MB / 52.1MB, 8.94MB/s




Processing Files (1 / 1)                : 100%|██████████| 52.1MB / 52.1MB, 7.67MB/s


Processing Files (1 / 1)                : 100%|██████████| 52.1MB / 52.1MB, 7.24MB/s
New Data Upload                         : 100%|██████████| 52.1MB / 52.1MB, 7.24MB/s
                                        : 100%|██████████| 52.1MB / 52.1MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 67.04ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :   9%|▉         | 4.24MB / 48.1MB, 10.6MB/s
Processing Files (0 / 1)                :  12%|█▏        | 5.83MB / 48.1MB, 9.72MB/s
Processing Files (0 / 1)                :  19%|█▊        | 9.01MB / 48.1MB, 11.3MB/s
Processing Files (0 / 1)                :  23%|██▎       | 11.1MB / 48.1MB, 11.1MB/s
Processing Files (0 / 1)                :  30%|██▉       | 14.3MB / 48.1MB, 11.9MB/s
Processing Files (0 / 1)                :  35%|███▌      | 17.0MB / 48.1MB, 12.1MB/s
Processing Files (0 / 1)                :  42%|████▏     | 20.1MB / 48.1MB, 12.6MB/s
Processing Files (0 / 1)                :  47%|████▋     | 22.8MB / 48.1MB, 12.7MB/s
Processing Files (0 / 1)                :  53%|█████▎    | 25.4MB / 48.1MB, 12.7MB/s
Processing Files (0 / 1)                :  61%|██████    | 29.2MB / 48.1MB, 13.2MB/s
Processing Files (0 / 1)                :  66%|██████▌   | 31.8MB / 48.1MB, 13.3MB/s
Processing Files (0 / 1)                :  73%|███████▎  | 35.0MB / 48.1MB, 13.5MB/s
Processing Files (0 / 1)                :  79%|███████▉  | 38.2MB / 48.1MB, 13.6MB/s
Processing Files (0 / 1)                :  86%|████████▌ | 41.3MB / 48.1MB, 13.8MB/s
Processing Files (0 / 1)                :  94%|█████████▎| 45.1MB / 48.1MB, 14.1MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 47.7MB / 48.1MB, 14.0MB/s




Processing Files (1 / 1)                : 100%|██████████| 48.1MB / 48.1MB, 10.9MB/s

Processing Files (1 / 1)                : 100%|██████████| 48.1MB / 48.1MB, 10.5MB/s
New Data Upload                         : 100%|██████████| 48.1MB / 48.1MB, 10.5MB/s
                                        : 100%|██████████| 48.1MB / 48.1MB
Creating parquet from Arrow format: 100%|██████████| 18/18 [00:00<00:00, 65.78ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :  13%|█▎        | 7.07MB / 53.4MB, 35.4MB/s
Processing Files (0 / 1)                :  17%|█▋        | 9.19MB / 53.4MB, 23.1MB/s
Processing Files (0 / 1)                :  21%|██        | 11.3MB / 53.4MB, 18.9MB/s
Processing Files (0 / 1)                :  27%|██▋       | 14.5MB / 53.4MB, 18.2MB/s
Processing Files (0 / 1)                :  32%|███▏      | 17.2MB / 53.4MB, 17.2MB/s
Processing Files (0 / 1)                :  37%|███▋      | 19.8MB / 53.4MB, 16.5MB/s
Processing Files (0 / 1)                :  43%|████▎     | 23.0MB / 53.4MB, 16.4MB/s
Processing Files (0 / 1)                :  49%|████▉     | 26.2MB / 53.4MB, 16.4MB/s
Processing Files (0 / 1)                :  55%|█████▌    | 29.4MB / 53.4MB, 16.3MB/s
Processing Files (0 / 1)                :  62%|██████▏   | 33.1MB / 53.4MB, 16.6MB/s
Processing Files (0 / 1)                :  68%|██████▊   | 36.3MB / 53.4MB, 16.5MB/s
Processing Files (0 / 1)                :  75%|███████▍  | 40.0MB / 53.4MB, 16.7MB/s
Processing Files (0 / 1)                :  81%|████████  | 43.2MB / 53.4MB, 16.6MB/s
Processing Files (0 / 1)                :  88%|████████▊ | 46.9MB / 53.4MB, 16.8MB/s
Processing Files (0 / 1)                :  94%|█████████▍| 50.1MB / 53.4MB, 16.7MB/s
Processing Files (0 / 1)                : 100%|█████████▉| 53.3MB / 53.4MB, 16.7MB/s



Processing Files (1 / 1)                : 100%|██████████| 53.4MB / 53.4MB, 13.4MB/s


Processing Files (1 / 1)                : 100%|██████████| 53.4MB / 53.4MB, 12.1MB/s
New Data Upload                         : 100%|██████████| 50.1MB / 50.1MB, 11.4MB/s
                                        : 100%|██████████| 53.4MB / 53.4MB
Uploading the dataset shards: 100%|██████████| 10/10 [01:07<00:00,  6.79s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/andstor/cvevc_candidates/commit/23d503befca0daab9dc03f7eeb738e06dd6cbcd5', commit_message='Upload dataset', commit_description='', oid='23d503befca0daab9dc03f7eeb738e06dd6cbcd5', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/andstor/cvevc_candidates', endpoint='https://huggingface.co', repo_type='dataset', repo_id='andstor/cvevc_candidates'), pr_revision=None, pr_num=None)

In [29]:
cve_cands_ds

Dataset({
    features: ['cve', 'desc', 'repo', 'commit_id', 'commit_message', 'diff', 'label', 'rank'],
    num_rows: 179473
})

In [30]:
cve_cands_ds_top10 = cve_cands_ds.filter(lambda x: x['rank'] <= 10)

Filter: 100%|██████████| 179473/179473 [00:01<00:00, 98695.43 examples/s]

In [ ]:
cve_cands_ds_top10.push_to_hub("andstor/cvevc_candidates", config_name="PatchFinder_top10", private=False, max_shard_size="250MB")

Creating parquet from Arrow format: 100%|██████████| 13/13 [00:00<00:00, 16.81ba/s]
Processing Files (0 / 0)                : |          |  0.00B /  0.00B

Processing Files (0 / 1)                :  31%|███       | 15.2MB / 49.9MB,   ???B/s
Processing Files (0 / 1)                :  35%|███▍      | 17.4MB / 49.9MB, 10.7MB/s

Processing Files (0 / 1)                :  44%|████▍     | 22.2MB / 49.9MB, 11.6MB/s
Processing Files (0 / 1)                :  50%|████▉     | 24.9MB / 49.9MB, 12.1MB/s
Processing Files (0 / 1)                :  56%|█████▋    | 28.1MB / 49.9MB, 12.9MB/s
Processing Files (0 / 1)                :  62%|██████▏   | 30.8MB / 49.9MB, 13.0MB/s
Processing Files (0 / 1)                :  67%|██████▋   | 33.4MB / 49.9MB, 13.0MB/s
Processing Files (0 / 1)                :  73%|███████▎  | 36.7MB / 49.9MB, 13.4MB/s
Processing Files (0 / 1)                :  79%|███████▉  | 39.3MB / 49.9MB, 13.4MB/s
Processing Files (0 / 1)                :  85%|████████▌ | 42.6MB / 49.9MB, 13.7MB/s
Processing Files (0 / 1)                :  92%|█████████▏| 45.8MB / 49.9MB, 13.9MB/s
Processing Files (0 / 1)                :  97%|█████████▋| 48.4MB / 49.9MB, 13.8MB/s
Processing Files (0 / 1)                :  99%|█████████▉| 49.5MB / 49.9MB, 13.2MB/s




Processing Files (1 / 1)                : 100%|██████████| 49.9MB / 49.9MB, 9.63MB/s


Processing Files (1 / 1)                : 100%|██████████| 49.9MB / 49.9MB, 8.66MB/s
New Data Upload                         : 100%|██████████| 38.4MB / 38.4MB, 8.66MB/s
                                        : 100%|██████████| 49.9MB / 49.9MB
Uploading the dataset shards: 100%|██████████| 1/1 [00:06<00:00,  6.73s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/andstor/cvevc_candidates/commit/153fbc99f592ad5594c1b4607b4b556eb3caedf1', commit_message='Upload dataset', commit_description='', oid='153fbc99f592ad5594c1b4607b4b556eb3caedf1', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/andstor/cvevc_candidates', endpoint='https://huggingface.co', repo_type='dataset', repo_id='andstor/cvevc_candidates'), pr_revision=None, pr_num=None)

# Random dataset

In [ ]:
from datasets import load_dataset, DatasetDict, Dataset

ds_cve = load_dataset("andstor/cvevc_cve")
ds_patches = load_dataset("andstor/cvevc_commits", "patches")
ds_nonpatches = load_dataset("andstor/cvevc_commits", "non_patches")
ds_mappings = load_dataset("andstor/cvevc_cve_commit_mappings")

Resolving data files:   0%|          | 0/140 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/83 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/96 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/140 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/83 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/96 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/140 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/83 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/96 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/79 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/52 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/58 [00:00<?, ?it/s]

In [ ]:
from tqdm import tqdm
import pandas as pd

ddict_100 = DatasetDict()
ddict_10 = DatasetDict()

for split in ["test"]:
    # Index for commit_id lookup
    cindex = {key: idx for idx, key in tqdm(enumerate(ds_cve[split]["cve"]), total=len(ds_cve[split]["cve"]), desc=f"Indexing CVEs {split}")}
    pindex = {key: idx for idx, key in tqdm(enumerate(ds_patches[split]["commit_id"]), total=len(ds_patches[split]["commit_id"]), desc=f"Indexing patch commits {split}")}
    npindex = {key: idx for idx, key in tqdm(enumerate(ds_nonpatches[split]["commit_id"]), total=len(ds_nonpatches[split]["commit_id"]), desc=f"Indexing non-patch commits {split}")}
    
    
    def mapping_to_record(example):
        cve = example["cve"]
        commit_id = example["commit_id"]
        
        cve_row = ds_cve[split][cindex[cve]]
        commit_row = None
        if commit_id in pindex: # Patch commit
            commit_row = ds_patches[split][pindex[commit_id]]
        else: # Non-patch commit
            commit_row = ds_nonpatches[split][npindex[commit_id]]
        
        if commit_row is not None:
            return {
                "cve": cve,
                "desc": cve_row["desc"],
                "repo": commit_row["repo"],
                "commit_id": commit_id,
                "commit_message": commit_row["commit_message"],
                "diff": commit_row["diff"],
                "label": example["label"],
            }
        else:
            return None
    
    cve_mappings = ds_mappings[split].to_pandas().groupby("cve")
    
    subset_100 = []
    subset_10 = []
    for cve, group_df in tqdm(cve_mappings):
        # select all patches for this group_df. use label == 1
        cve_data = []
        patches = group_df[group_df["label"] == 1]
        # now select 10 - len(patches) non-patches


        non_patches_pool = group_df[group_df["label"] == 0]
        non_patches_pool = non_patches_pool.sample(min(len(non_patches_pool), 100), replace=False, random_state=42)

        needed = max(0, 100 - len(patches))
        non_patches = non_patches_pool[:needed]
        cve_df = pd.concat([patches, non_patches])
        cve_df = cve_df.apply(mapping_to_record, axis=1, result_type='expand')
        subset_100.append(cve_df)
        
        needed = max(0, 10 - len(patches))
        non_patches = non_patches_pool[:needed]
        cve_df = pd.concat([patches, non_patches])
        cve_df = cve_df.apply(mapping_to_record, axis=1, result_type='expand')
        subset_10.append(cve_df)

    final_100 = pd.concat(subset_100, ignore_index=True)
    final_10 = pd.concat(subset_10, ignore_index=True)
    ddict_100[split] = Dataset.from_pandas(final_100)
    ddict_10[split] = Dataset.from_pandas(final_10)

Indexing CVEs train: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8963/8963 [00:00<00:00, 69538.74it/s]
Indexing patch commits train: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11620/11620 [00:00<00:00, 70418.66it/s]
Indexing non-patch commits train: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3632163/3632163 [00:52<00:00, 68673.79it/s]
 74%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                    | 5970/8019 [03:58<02:29, 13.73it/s]

In [ ]:
ddict_10.push_to_hub("andstor/cvevc_candidates", "random_10", private=False, max_shard_size="250MB")
ddict_100.push_to_hub("andstor/cvevc_candidates", "random_100", private=False, max_shard_size="250MB")